# =============================================================================
# PROMETHEUS CONFIGURATION FOR REDIS ENTERPRISE
# =============================================================================
# Generated by Terraform - redis_enterprise_monitoring module
# Docs: https://redis.io/docs/latest/integrate/prometheus-with-redis-enterprise/
# =============================================================================

global:
  scrape_interval: ${scrape_interval}
  evaluation_interval: ${scrape_interval}

# =============================================================================
# SCRAPE CONFIGS
# =============================================================================

scrape_configs:
  # ---------------------------------------------------------------------------
  # Redis Enterprise Cluster Metrics (via cluster FQDN)
  # ---------------------------------------------------------------------------
  - job_name: 'redis-enterprise-cluster'
    scrape_interval: ${scrape_interval}
    scrape_timeout: ${scrape_interval}
    metrics_path: ${metrics_path}
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - '${cluster_fqdn}:${metrics_port}'
        labels:
          cluster: '${cluster_fqdn}'

  # ---------------------------------------------------------------------------
  # Redis Enterprise Node Metrics (individual nodes for redundancy)
  # ---------------------------------------------------------------------------
  - job_name: 'redis-enterprise-nodes'
    scrape_interval: ${scrape_interval}
    scrape_timeout: ${scrape_interval}
    metrics_path: ${metrics_path}
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
%{ for node_ip in cluster_nodes ~}
          - '${node_ip}:${metrics_port}'
%{ endfor ~}
        labels:
          cluster: '${cluster_fqdn}'

  # ---------------------------------------------------------------------------
  # Prometheus Self-Monitoring
  # ---------------------------------------------------------------------------
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'
